on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: build
      run: dotnet build -c Release
    - name: publish
      run: dotnet publish -c Release --no-build Raytracer/Raytracer.csproj -o output/Raytracer
    - uses: actions/upload-artifact@v1
      with:
        name: Raytracer
        path: output